#DEV environment

app:
  message: This is the property file fo the ${spring.application.name} especific to DEV Enviromente

spring:
   datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2mem:db;DB_CLOSE_DELAY=-1
   username: sa
   password: sa

